"""
Task hygiene report — aggregate active tasks for dashboard and governance.

Used by: task.py report [--write]
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .paths import DIR_TASKS, DIR_WORKFLOW
from .tasks import children_progress, get_all_statuses, iter_active_tasks
from .types import TaskInfo

_TERMINAL_STATUSES = frozenset({"completed", "done"})
_ACTIVE_STATUSES = frozenset({"in_progress", "open", "review"})
_STALE_DAYS = 14


@dataclass
class TaskHygieneIssue:
    kind: str
    dir_name: str
    detail: str


@dataclass
class TaskReport:
    generated_at: str
    total: int
    by_status: dict[str, int] = field(default_factory=dict)
    by_priority: dict[str, int] = field(default_factory=dict)
    p0_p1_open: list[TaskInfo] = field(default_factory=list)
    archive_candidates: list[TaskInfo] = field(default_factory=list)
    stale_parents: list[tuple[TaskInfo, str]] = field(default_factory=list)
    issues: list[TaskHygieneIssue] = field(default_factory=list)
    hot_tasks: list[tuple[TaskInfo, int]] = field(default_factory=list)

    def to_markdown(self, repo_root: Path) -> str:
        lines: list[str] = [
            "# Trellis Task Dashboard",
            "",
            f"> Auto-generated by `python .trellis/scripts/task.py report --write`",
            f"> Last run: **{self.generated_at}** (UTC)",
            "",
            "Governance playbook: [GOVERNANCE.md](./GOVERNANCE.md)",
            "",
            "## Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Active tasks | **{self.total}** |",
        ]
        for status, count in sorted(self.by_status.items(), key=lambda x: (-x[1], x[0])):
            lines.append(f"| `{status}` | {count} |")

        lines.extend(["", "## P0 / P1 still open", ""])
        if self.p0_p1_open:
            lines.append("| Task | Priority | Status | Title |")
            lines.append("|------|----------|--------|-------|")
            for t in sorted(self.p0_p1_open, key=lambda x: (x.priority, x.dir_name)):
                rel = f"{DIR_WORKFLOW}/{DIR_TASKS}/{t.dir_name}"
                lines.append(
                    f"| [`{t.dir_name}`](./{t.dir_name}/task.json) | {t.priority} | {t.status} | {t.title} |"
                )
        else:
            lines.append("_None._")

        lines.extend(["", "## Archive candidates", ""])
        lines.append(
            "Tasks with `status=completed|done` still in active tree — run `task.py archive <name>`."
        )
        lines.append("")
        if self.archive_candidates:
            for t in sorted(self.archive_candidates, key=lambda x: x.dir_name):
                lines.append(f"- `{t.dir_name}` — {t.title}")
        else:
            lines.append("_None._")

        lines.extend(["", "## Stale parents (all children done)", ""])
        if self.stale_parents:
            for t, progress in self.stale_parents:
                lines.append(f"- `{t.dir_name}` ({t.status}) {progress} — consider archive or `set-status completed`")
        else:
            lines.append("_None._")

        lines.extend(["", "## Hygiene issues", ""])
        if self.issues:
            lines.append("| Kind | Task | Detail |")
            lines.append("|------|------|--------|")
            for issue in self.issues[:40]:
                lines.append(f"| {issue.kind} | `{issue.dir_name}` | {issue.detail} |")
            if len(self.issues) > 40:
                lines.append(f"| … | | _{len(self.issues) - 40} more_ |")
        else:
            lines.append("_No issues detected._")

        lines.extend(["", "## Recently touched (mtime)", ""])
        if self.hot_tasks:
            lines.append("| Task | Days idle | Status | Priority |")
            lines.append("|------|-----------|--------|----------|")
            for t, days in self.hot_tasks[:15]:
                lines.append(f"| `{t.dir_name}` | {days} | {t.status} | {t.priority} |")
        else:
            lines.append("_None._")

        lines.extend([
            "",
            "## Commands",
            "",
            "```bash",
            "python .trellis/scripts/task.py list",
            "python .trellis/scripts/task.py list --status completed",
            "python .trellis/scripts/task.py archive <name>",
            "python .trellis/scripts/task.py set-status <name> completed",
            "python .trellis/scripts/task.py report --write",
            "```",
            "",
        ])
        return "\n".join(lines)


def _dir_idle_days(task_dir: Path) -> int:
    """Days since newest mtime under task directory."""
    now = datetime.now(timezone.utc)
    latest = task_dir.stat().st_mtime
    for p in task_dir.rglob("*"):
        if p.is_file():
            latest = max(latest, p.stat().st_mtime)
    delta = now.timestamp() - latest
    return max(0, int(delta // 86400))


def _task_dir_mtime(task_dir: Path) -> float:
    latest = task_dir.stat().st_mtime
    for p in task_dir.rglob("*"):
        if p.is_file():
            latest = max(latest, p.stat().st_mtime)
    return latest


def build_task_report(tasks_dir: Path) -> TaskReport:
    """Analyze all active tasks and return a structured report."""
    tasks = list(iter_active_tasks(tasks_dir))
    all_statuses = get_all_statuses(tasks_dir)
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    by_status: Counter[str] = Counter()
    by_priority: Counter[str] = Counter()
    issues: list[TaskHygieneIssue] = []
    archive_candidates: list[TaskInfo] = []
    p0_p1_open: list[TaskInfo] = []
    stale_parents: list[tuple[TaskInfo, str]] = []
    mtime_rank: list[tuple[TaskInfo, int, float]] = []

    for t in tasks:
        by_status[t.status] += 1
        by_priority[t.priority] += 1
        idle = _dir_idle_days(t.directory)
        mtime_rank.append((t, idle, _task_dir_mtime(t.directory)))

        if t.status in _TERMINAL_STATUSES:
            archive_candidates.append(t)

        if t.priority in ("P0", "P1") and t.status not in _TERMINAL_STATUSES:
            p0_p1_open.append(t)

        if not (t.directory / "prd.md").is_file():
            issues.append(TaskHygieneIssue("missing-prd", t.dir_name, "no prd.md"))

        if t.children:
            progress = children_progress(t.children, all_statuses)
            done_part = progress.strip(" []")
            if done_part and "/" in done_part:
                done, total = done_part.replace(" done", "").split("/")
                if done == total and t.status in _ACTIVE_STATUSES:
                    stale_parents.append((t, progress.strip()))

        if t.status in _ACTIVE_STATUSES and idle >= _STALE_DAYS:
            issues.append(
                TaskHygieneIssue(
                    "stale-active",
                    t.dir_name,
                    f"in active status {idle}d without file updates",
                )
            )

    mtime_rank.sort(key=lambda x: x[2], reverse=True)
    hot_tasks = [(t, idle) for t, idle, _ in mtime_rank[:15]]

    return TaskReport(
        generated_at=now_iso,
        total=len(tasks),
        by_status=dict(by_status),
        by_priority=dict(by_priority),
        p0_p1_open=p0_p1_open,
        archive_candidates=archive_candidates,
        stale_parents=stale_parents,
        issues=issues,
        hot_tasks=hot_tasks,
    )


def write_dashboard(repo_root: Path, report: TaskReport) -> Path:
    """Write DASHBOARD.md under .trellis/tasks/."""
    out = repo_root / DIR_WORKFLOW / DIR_TASKS / "DASHBOARD.md"
    out.write_text(report.to_markdown(repo_root), encoding="utf-8")
    return out
